### ISSUE TITLE
Server segfaults upon GET .well-known/core

### ISSUE THREAD

**Issue by bsmelo** [Lobaro/coap-go#3]
I was able to `go run main.go`, but when I used Firefox Copper to retrieve the available resources on the sample application, although I got a response at Firefox, the application crashed with the following details:

```
 $ go run main.go
2017/08/23 15:04:58 Allocated go memory at 0x7e7210
CoAP_init!
CoAP Available memory: 4096 bytes at 0x7e7210
CoAP Interaction size: 128 byte
CoAP_Res_t size: 64 byte
CoAP_Message_t size: 48 byte
CoAP_option_t size: 24 byte
CoAP_Observer_t size: 56 byte
2017/08/23 15:04:58 Init liblobarocoap
2017/08/23 15:04:58 Creating UDP CoAP socket
- CoAP_CreateInterfaceSocket(): listening... IfID: 1 
2017/08/23 15:05:21 Received UDP Data@ 127.0.0.1 : 38403 => [64 1 40 120 187 46 119 101 108 108 45 107 110 111 119 110 4 99 111 114 101]

<<<<<<<<<<<<<<<<<<<<<<
New Datagram received [21 Bytes], Interface #1
Sending Endpoint: IPv4, 127.0.0.1:38403
----------------------------
*Type: CON (0x00)
*Token: 0 Byte -> 0
*Code: 0.01 (0x01) [REQ_GET]
*MessageId: 10360
*Option #11 (Length=11) -> .[2e] w[77] e[65] l[6c] l[6c] -[2d] k[6b] n[6e] o[6f] w[77] n[6e]
*Option #11 (Length=4) -> c[63] o[6f] r[72] e[65]
*Timestamp: 1503511521
----------------------------
<<<<<<<<<<<<<<<<<<<<<<
- WellKnown_GetHandler(): res cnt:1 temp alloc:192

>>>>>>>>>>>>>>>>>>>>>>
Send Message [27 Bytes], Interface #1
Receiving Endpoint: IPv4, 127.0.0.1:38403
0x60(`) 0x45(E) 0x28(() 0x78(x) 0xc1(�) 0x28(() 0xff(�) 0x3c(<) 0x2e(.) 0x77(w) 0x65(e) 0x6c(l) 0x6c(l) 0x2d(-) 0x6b(k) 0x6e(n) 0x6f(o) 0x77(w) 0x6e(n) 0x2f(/) 0x63(c) 0x6f(o) 0x72(r) 0x65(e) 0x2f(/) 0x3e(>) 0x2c(,) 
----------------------------
*Type: ACK (0x02)
*Token: 0 Byte -> 0
*Code: 2.05 (0x45) 
*MessageId: 10360
*Option #12 (Length=1) -> ([28]
*Payload (20 Byte): "<.well-2017/08/23 15:05:21 Sending UDP Data to  127.0.0.1:38403  =>  [96 69 40 120 193 40 255 60 46 119 101 108 108 45 107 110 111 119 110 47 99 111 114 101 47 62 44]
known/core/>,"
*Timestamp: 0
----------------------------
>>>>>>>>>>FAIL>>>>>>>>>>
(!!!) SendResp(): Internal socket error on sending response! MiD: 10360Releasing Interaction...
- CoAP mem usage: dynamic: [544] dynamic+static: [544] free: [3548] biggest shunk: [139852725095900] get/releases: [139852725092363|2]
SIGSEGV: segmentation violation
PC=0x40586d
signal arrived during cgo execution

runtime.cgocallbackg()
        /usr/lib/go/src/pkg/runtime/cgocall.c:267 +0x89 fp=0x7f329a4e7ec0
runtime.cgocallback_gofunc(0x40edf3, 0x405730, 0x7f329a4e7f38)
        /usr/lib/go/src/pkg/runtime/asm_amd64.s:711 +0x67 fp=0x7f329a4e7ed0
runtime.asmcgocall(0x405730, 0x7f329a4e7f38)
        /usr/lib/go/src/pkg/runtime/asm_amd64.s:618 +0x2d fp=0x7f329a4e7ed8
runtime.cgocall(0x405730, 0x7f329a4e7f38)
        /usr/lib/go/src/pkg/runtime/cgocall.c:149 +0x133 fp=0x7f329a4e7f20
github.com/Lobaro/coap-go/coap-old._Cfunc_CoAP_doWork(0x45bce8)
        github.com/Lobaro/coap-go/coap-old/_obj/_cgo_defun.c:104 +0x31 fp=0x7f329a4e7f38
github.com/Lobaro/coap-go/coap-old.doWork()
        /home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/go_api.go:74 +0x1a fp=0x7f329a4e7f40
github.com/Lobaro/coap-go/coap-old.func·001()
        /home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/go_api.go:47 +0x28 fp=0x7f329a4e7fa0
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1394 fp=0x7f329a4e7fa8
created by github.com/Lobaro/coap-go/coap-old.init·1
        /home/bruno/go/src/github.com/Lobaro/coap-go/coap-old/go_api.go:51 +0x26

goroutine 1 [sleep]:
time.Sleep(0x5f5e100)
        /usr/lib/go/src/pkg/runtime/time.goc:31 +0x31
main.handleUdpIncoming(0xc210000090)
        /home/bruno/Dropbox/coap-apps/todo/coap-go/main.go:55 +0x3ea
main.main()
        /home/bruno/Dropbox/coap-apps/todo/coap-go/main.go:29 +0x384

goroutine 3 [syscall]:
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1394

goroutine 5 [chan receive]:
main.handleUdpOutgoing(0xc210000090)
        /home/bruno/Dropbox/coap-apps/todo/coap-go/main.go:34 +0x3e
created by main.main
        /home/bruno/Dropbox/coap-apps/todo/coap-go/main.go:28 +0x374

rax     0x0
rbx     0x7f3200000000
rcx     0x88
rdx     0x0
rdi     0x7f329a271400
rsi     0x7f329a2729e0
rbp     0x7ef2e0
rsp     0x7f3298daadd0
r8      0x7f3298dab700
r9      0x383933315b203a73
r10     0x7f329a26f6a0
r11     0x0
r12     0x0
r13     0x0
r14     0x65
r15     0x10
rip     0x40586d
rflags  0x10206
cs      0x33
fs      0x0
gs      0x0
exit status 2
```

I see it's a `socket error`, but it also seems to be coming from `cgo` (as I said, I have basically zero knowledge of `go` itself)... Is this a problem on the code (i.e. actually socket-related), or something related to my setup (i.e. compiler, architecture, OS...)?

Thanks & Regards,
Bruno Melo.

**Comment by niondir** [comment]
Thanks for testing it so far, it was not used for some time ;)

To the actual problem: It Seems like the mapping between C and Go is broken somehow.

It looks like the C function `CoAP_SendMsg` in (https://github.com/Lobaro/lobaro-coap/blob/772fabcf9d4dbf4d1429d149d7988c8cb30cea0a/src/coap_message.c#L396) fails at line 450 where the callback to Go is called via Function Pointer: `NetTransmit_fn SendPacket = pSocket->Tx;`

The Tx function is responsible for sending the Packet over the wire which is implemented in Go.

Can't say more without more debugging :) But registering endpoints is not implemented yet anyway.

I also like to repeat that the Go to C binding is not finished (Registering endpoints is not working) plus the underlying C Code is a old copy of the liblobaro-coap C lib. Since then it evolved quiet a bit. I was planning to replace the C code by a `.a` file and linking to pre-build C code. This would need some work to adopt the wrapper to the most resent API. Thats also the reason why the package is called `coap-old`.

**Comment by bsmelo** [comment]
Ohh OK, got it. =)

I see it better now that this library probably doesn't fit my needs, as you said in the last comment at the other Github issue. To explain it a little bit, I'm doing research which includes testing the server-side of CoAP implementations out there. To that end, I started looking for any CoAP implementation available to me on the Internet -- with a focus on organization-backed and/or commercial/widely used projects such as the `lobaro-coap-*` ones --, and that's how I found out about `lobaro-coap-go` as well.

Anyway, thanks a lot for all clarification about the state of this implementation so far! :)

**Comment by niondir** [comment]
You might be more successful with our C implementation. Since it runs on micro controllers, there is no network stack included. When using the C lib on Linux you could easily bind any UDP / TCP / Serial connection to the socket interface an use it. In embedded environments we just bind some UART read/write function to the socket struct. It's actually used in production.

If you have questions about getting the C implementation to run, feel free to open issues in https://github.com/Lobaro/lobaro-coap

**Comment by bsmelo** [comment]
Hi! =)

Just trying to get an update: Is it working right now? I had a look at the C implementation, but I couldn't find an example application that runs on Linux, only the one for ESP8266.
This repository (go-coap) would better serve my purposes, since it has the example applications already.

Thanks again!

**Comment by niondir** [comment]
Well, I have no intentions to further develop the CGO based wrapper around our Coap C Library. Instead I would rather implement a CoAP Server in Go if needed.

If you want to help to finish the wrapper I'm glad to help with any pull requests. But I don't expect it to be an easy task.

I can only recommend to use the lobaro-coap C implementations. It's designed for embedded Systems but can run on any other platform, since it has no dependencies but the stdlib.
All required functions are available in https://github.com/Lobaro/lobaro-coap/blob/master/src/liblobaro_coap.h

To get the lib running take a look at the following functions:
* `CoAP_Init`
* `CoAP_CreateResource`
* `CoAP_HandleIncomingPacket`
* `CoAP_doWork`
